[project]
name = "pythonplugin"
version = "0.1.0"
description = "Bosbase python plugin"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.124.0",
    "gunicorn>=23.0.0",
]
