[package]
name = "components"
version = "0.1.0"
edition = "2024"

[dependencies]

[[bin]]
name = "tokio-redis"
path = "src/tokio-redis.rs"

[[bin]]
name = "tokio-postgres"
path = "src/tokio-postgres.rs"